name: cat_breeds
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^3.2.1
  freezed: ^3.2.5
  envied: ^1.3.3
  envied_generator: ^1.1.1
  json_annotation: ^4.11.0
  dio: ^5.9.1
  retrofit: ^4.9.2
  dartz: ^0.10.1
  flutter_riverpod: ^3.2.1
  freezed_annotation: ^3.1.0
  riverpod_annotation: ^4.0.2
  go_router: ^17.1.0
  lottie: ^3.3.2
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.3
  build_runner: ^2.11.1
  json_serializable: ^6.7.1
  retrofit_generator: ^10.2.1

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf
    - family: StoryScript
      fonts:
        - asset: assets/fonts/StoryScript.ttf
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
